### ISSUE TITLE
Manatools manaservice bug

### ISSUE THREAD

**Issue by ozky** [xquiet/manatools#3]
I found another bug in Cauldron manatools systemd services don't work at all.
I try to stick off some service from box i get this screen.
![mpan](https://cloud.githubusercontent.com/assets/1551665/15042377/f567ff64-12cb-11e6-8108-e1ee767cd940.jpeg)
Btw there is now error with invalid content in shadow lock manauser,found bug report in our bugzilla.
https://bugs.mageia.org/show_bug.cgi?id=16668

**Comment by anaselli** [comment]
Please open different issues on different tools, otherwise we will certainly miss some...
Did you run mana service as root or as user? and does that happen for any services you try to stop (disable?)

**Comment by anaselli** [comment]
Have you tried  to disable network haven't you? It seems that dbus apis for services don't work for sysv services, systemctl seems to though. If so you cannot say it does not work at all...

**Comment by ozky** [comment]
Yes i try to disable it because i put network manager to default,i run that from root started mpan.
Systemctl works out of box no problems to use it,mcc have no this problem at all.
I'll open seperate bug to that other one.

**Comment by anaselli** [comment]
this [commit](https://github.com/xquiet/manatools/commit/3092a85563c21fc857dc58019e8df564fa8e21cc) should fix your issue, but once legacy services are disabled you cannot see them in manaservice (and drakxervices as well if I'm not wrong) you have to enable them by hands. Since legacy services should disappear i think adding an ad-hoc code to manage them should be avoided, and i would close this issue in this way. Please let me know if the patch is ok for you.

**Comment by ozky** [comment]
Sorry for late answer got some busy today but will try your patch tomorrow.

**Comment by ozky** [comment]
It fixes this bug i got my time to do it,yesterday i needed to watch some ice hockey when finland beat belarussia. :)

**Comment by anaselli** [comment]
thanks
